### PR TITLE
Add support for sending change events.

### PR DESCRIPTION
**Pull request by adamvaughan**
PagerDuty recently release a new change events feature that allows tracking modifications to your services in order to assist with incident triage. Sending change events closely mimics using the Events V2 API to send alerts/incidents with a few minor differences - primarily, there are fewer required fields and the no support for dedupe keys.

### CODE REVIEW

**Comment by dikhan** [comment]
Hi @adamvaughan,

Thanks for contributing! I had an initial pass at the changes and they looked good to me. Reading through the [Change Events](https://developer.pagerduty.com/docs/events-api-v2/send-change-events/) docs, I noticed the Change Events feature is in Early Access at the moment, pasting below the informative message from that page for the reference:

````
Change Events are in Early Access
PagerDuty change events are not yet available to all customers and the API specification is subject to change until it is generally released. Request early access here (select "Change events for incident resolution").
````

Given that the feature is not in GA, I am hesitant to merging this PR considering the API spec is subject to change as stated above before it goes GA.

I would be happy to cicle back to this PR once the feature is GA and do a full review then. Leaving the PR open though so the community can benefit from this changes in the meantime and can start trying out the Change Events through the client. Hopefully the feature gets to GA soon and we can integrate this changes into the repo.

Hope this makes sense, let me know if you have any concerns with it.

Thanks again for the great contribution!
Dani

**Comment by adamvaughan** [comment]
Thanks Dani! I'll follow up here once it goes GA 👍

**Comment by adamvaughan** [comment]
Hi Dani, just wanted to drop a note here that the Change Events feature is GA now. 

Thanks,
Adam

**Comment by dikhan** [comment]
> Hi Dani, just wanted to drop a note here that the Change Events feature is GA now.
> 
> Thanks,
> Adam

Thanks for the follow up @adamvaughan , I will take a look at the PR this weekend.

**Review by dikhan — CHANGES_REQUESTED** [review]
Hi @adamvaughan 

Just did another review and code wise everything is looking good. The only thing we are missing is updating the docs to include info about the newly added support for the change event API. Would you be able to take a crack at it updating the [Getting started docs](https://github.com/dikhan/pagerduty-client#getting-started)?

Once that's done we should be good to merge this bad boy :)

Thanks,
Dani

**Comment by dikhan** [comment]
Hi @adamvaughan, had some free cycles so I went ahead and updated the docs. Will be leaving the PR open for few more days in case you want to review the updated docs and provide some feedback. 

Otherwise this is good to go now.

Thanks again for contributing!

**Review by dikhan — APPROVED** [review]

**Comment by adamvaughan** [comment]
@dikhan thanks for making those updates, I've been swamped lately and haven't had a chance to get to it. This looks great to me!

**Comment by dikhan** [comment]
> @dikhan thanks for making those updates, I've been swamped lately and haven't had a chance to get to it. This looks great to me!

Thx for reviewing it @adamvaughan , will go ahead and merge this PR now.

**Pull request merged**
